###
POST {{domain}}/article
Content-Type: application/json

{
  "title": "title333",
  "body": "body2",
  "authorId": 1234
}

### get
GET {{domain}}/article/1
Content-Type: application/json

### get all
GET http://localhost:8080/article/all
Content-Type: application/json

### update
PUT http://localhost:8080/article/1
Content-Type: application/json

{
  "title": "title matched"
}

### delete
DELETE http://localhost:8080/article/1
Content-Type: application/json